# Generated by Django 5.2.7 on 2025-11-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroNUAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pais', models.CharField(choices=[('chile', 'Chile'), ('argentina', 'Argentina'), ('colombia', 'Colombia')], max_length=50)),
                ('identificador_tributario', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
