# Generated by Django 5.2.7 on 2025-11-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (ej: Renta Fija, Renta Variable)', max_length=100, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
            },
        ),
        migrations.AlterField(
            model_name='registronuam',
            name='pais',
            field=models.CharField(choices=[('chile', 'Chile'), ('colombia', 'Colombia'), ('peru', 'Perú')], max_length=50),
        ),
    ]
