# Generated by Django 5.2.7 on 2025-11-04 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0002_clasificacion_alter_registronuam_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('nombre_dato', models.CharField(help_text='Nombre o ID del dato', max_length=255)),
                ('fecha_dato', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='ItemApp.clasificacion')),
            ],
            options={
                'verbose_name': 'Dato Tributario',
                'verbose_name_plural': 'Datos Tributarios',
            },
        ),
    ]
