# Generated by Django 5.2.7 on 2025-11-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0003_datotributario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registronuam',
            name='pais',
            field=models.CharField(choices=[('chile', 'Chile'), ('colombia', 'Colombia'), ('peru', 'Perú'), ('argentina', 'Argentina'), ('mexico', 'México'), ('brasil', 'Brasil'), ('ecuador', 'Ecuador'), ('venezuela', 'Venezuela'), ('uruguay', 'Uruguay'), ('paraguay', 'Paraguay'), ('bolivia', 'Bolivia')], max_length=100),
        ),
    ]
