# Generated by Django 5.2.7 on 2025-11-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0006_clasificacion_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.CharField(choices=[('AC', 'Acciones'), ('FI', 'Fondos de Inversión'), ('CF', 'Cuotas de Fondos')], default='AC', max_length=10)),
                ('instrumento', models.CharField(max_length=100, verbose_name='Instrumento / Nemo')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_pago', models.DateField()),
                ('secuencia_evento', models.BigIntegerField(help_text='ID único del evento (ej: 100000809)', unique=True)),
                ('anio', models.IntegerField(verbose_name='Año Tributario')),
                ('isfut', models.BooleanField(default=False, verbose_name='ISFUT')),
                ('ingreso_por_montos', models.BooleanField(default=False, verbose_name='Ingreso por Montos')),
                ('valor_historico', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('factor_08', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F08 No Constitutiva Renta')),
                ('factor_09', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F09 Impto 1ra Cat Afecto')),
                ('factor_10', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F10 Impto Tasa Adic Exento')),
                ('factor_11', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F11 Incremento Impto 1ra Cat')),
                ('factor_12', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F12 Impto 1ra Cat Exento')),
                ('factor_13', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F13 Impto 1ra Cat Afecto Sin Dev')),
                ('factor_14', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F14 Impto 1ra Cat Exento Sin Dev')),
                ('factor_15', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F15 Creditos Impuestos Externos')),
                ('factor_16', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F16 No Constitutiva Acogido Impto')),
                ('factor_17', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F17 No Const. Dev Capital Art.17')),
                ('factor_18', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F18 Rentas Exentas Impto GC')),
                ('factor_19', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F19 Ingreso no Constitutivo')),
                ('factor_19A', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F19A Ingreso no Const. Renta')),
                ('factor_20', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F20 Sin Derecho a Dev')),
                ('factor_21', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F21 Con Derecho a Dev')),
                ('factor_22', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F22 Sin Derecho a Dev')),
                ('factor_23', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F23 Con Derecho a Dev')),
                ('factor_24', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F24 Sin Derecho a Dev')),
                ('factor_25', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F25 Con Derecho a Dev')),
                ('factor_26', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F26 Sin Derecho a Dev')),
                ('factor_27', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F27 Con Derecho a Dev')),
                ('factor_28', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F28 Credito por IPE')),
                ('factor_29', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F29 Sin Derecho a Dev')),
                ('factor_30', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F30 Con Derecho a Dev')),
                ('factor_31', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F31 Sin Derecho a Dev')),
                ('factor_32', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F32 Con Derecho a Dev')),
                ('factor_33', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F33 Credito por IPE')),
                ('factor_34', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F34 Cred. Impto Tasa Adic.')),
                ('factor_35', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F35 Tasa Efectiva Cred FUT')),
                ('factor_36', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F36 Tasa Efectiva Cred FUNT')),
                ('factor_37', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='F37 Dev Capital Art 17 num 7')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calificación Tributaria (UI)',
                'verbose_name_plural': 'Calificaciones Tributarias (UI)',
            },
        ),
    ]
