# Generated by Django 5.2.7 on 2025-11-30 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0007_calificaciontributaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registronuam',
            name='pais',
            field=models.CharField(choices=[('chile', 'Chile'), ('colombia', 'Colombia'), ('peru', 'Perú')], max_length=100),
        ),
        migrations.CreateModel(
            name='SolicitudEdicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(default='Solicito desbloqueo para corregir un error.')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
                ('dato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemApp.datotributario')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
