# Generated by Django 5.2.7 on 2025-11-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0008_alter_registronuam_pais_solicitudedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datotributario',
            name='desbloqueado',
            field=models.BooleanField(default=False, help_text='Si es True, el usuario puede borrarlo fuera de tiempo'),
        ),
    ]
